var User = require('./controller/user.js');
var Question = require('./controller/question.js')
var Answer = require('./controller/answer.js')
var Index = require('./controller/index.js')
var Comment = require('./controller/comment.js')
var Vote = require('./controller/vote.js')
var Attention = require('./controller/attention.js')
var Follow = require('./controller/follow.js')

module.exports = function (app) {
	app.post('/user/phoneLogin',User.phoneLogin)
	app.post('/user/pwLogin',User.pwLogin)
	app.post('/user/getCode',User.getCode)
	app.post('/user/regist',User.toRegist)
	app.post('/user/getIdByToken',User.getIdByToken)
	app.post('/user/getNowUserInfo',User.getNowUserInfo)
	app.post('/user/saveInfo',User.saveInfo)
	app.get('/user/test',User.test)
	app.post('/user/getInfoById',User.getInfoById)
	app.post('/user/setAvatar',User.setAvatar)
	app.post('/user/cut',User.cut)
	app.post('/user/test2',User.test2)
	app.post('/question/insert',Question.insert)
	app.post('/question/read',Question.read)
	app.get('/question/test',Question.test)
	app.post('/question/detail',Question.detail)
	app.post('/answer/insert',Answer.insert)
	app.get('/answer/test',Answer.test)
	app.post('/answer/read',Answer.read)
	app.post('/comment/insert',Comment.insert)
	app.post('/comment/insert/question',Comment.insertToQuestion)
	app.post('/comment/read',Comment.read)
	app.post('/comment/read/question',Comment.readToQuestion)
	app.post('/comment/getConversation',Comment.getConversation)
	app.get('/comment/test',Comment.test)
	app.post('/vote/question',Vote.voteQuestion)
	app.post('/vote/answer',Vote.voteAnswer)
	app.post('/vote/comment',Vote.voteComment)
	app.post('/attention/question/add',Attention.attentionQuestionAdd)
	app.post('/attention/question/read',Attention.attentionQuestionRed)
	app.post('/follow/followTarget',Follow.followTarget)
	app.post('/follow/userBind',Follow.userBind)
	app.post('/user/readApprove',User.readApprove)
	app.post('/follow/user/fans',Follow.userFans)
	app.post('/follow/user/follow',Follow.userFollow)
	app.post('/user/read/answer',User.readUserAnswer)
	app.post('/user/read/question',User.readUserQuestion)
	app.post('/question/detailUser',Question.detailUser)
}